USE DATABASE KLA_SUPPLY_CHAIN;
USE SCHEMA APP;

CREATE OR REPLACE TABLE WAREHOUSE_INVENTORY (
    WAREHOUSE_ID        VARCHAR,
    WAREHOUSE_CITY      VARCHAR,
    COUNTRY_CODE        VARCHAR(3),
    PART_ID             VARCHAR,
    QTY_ON_HAND         INT,
    QTY_IN_TRANSIT      INT,
    QTY_BACKORDERED     INT,
    REORDER_POINT       INT,
    BATCH_LOT           VARCHAR,
    HOLDING_COST_DAILY  FLOAT
);

CREATE OR REPLACE TABLE ESCALATION_DEMANDS (
    CASE_ID             VARCHAR,
    CUSTOMER            VARCHAR,
    DESTINATION_CITY    VARCHAR,
    DESTINATION_LAT     FLOAT,
    DESTINATION_LON     FLOAT,
    PART_ID             VARCHAR,
    SEVERITY            VARCHAR,
    SLA_REMAINING_HRS   INT,
    REVENUE_AT_RISK     FLOAT,
    SLA_PENALTY_RATE    FLOAT
);

CREATE OR REPLACE TABLE TARIFF_RATES (
    ORIGIN_COUNTRY      VARCHAR(3),
    DEST_COUNTRY        VARCHAR(3),
    TARIFF_RATE_PCT     FLOAT,
    FTA_AGREEMENT       VARCHAR,
    SHIPPING_DAYS       INT,
    BASE_FREIGHT        FLOAT
);

CREATE OR REPLACE TABLE OPT_SCENARIOS (
    SCENARIO_ID         VARCHAR DEFAULT UUID_STRING(),
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    LABEL               VARCHAR,
    PARAMS_JSON         VARIANT
);

CREATE OR REPLACE TABLE OPT_RESULTS (
    RUN_ID              VARCHAR DEFAULT UUID_STRING(),
    SCENARIO_ID         VARCHAR,
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    TOTAL_COST          FLOAT,
    SLA_COVERAGE        FLOAT,
    TRANSFERS_JSON      VARIANT,
    ASSIGNMENTS_JSON    VARIANT,
    ROUTES_JSON         VARIANT
);
